SFDC/src/objects/Accompaniment__c.object
<CustomObject>
    <description>This is the Relation that is linked to an Interaction.</description>
    <fields>
        <fullName>Interaction__c</fullName>
        <description>The Interaction to which this Accompaniment is related to.</description>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Accompaniments</relationshipLabel>
        <relationshipName>Accompaniments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Of_Accompaniment__c</fullName>
        <description>Role of the accompaniment</description>
        <label>Accompaniment Role</label>
        <picklist>
            <picklistValues>
                <fullName>Silent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Accompaniment</label>
    <nameField>
        <displayFormat>Accompaniment-{000}</displayFormat>
        <label>Accompaniment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accompaniments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/classes/triggerDelInteractionChildrenTest.cls
@istest
public class triggerDelInteractionChildrenTest{
    static testmethod void unittest(){
   test.starttest();
   Interaction__C inte = new Interaction__C();
   //Interaction__C inte1 = new Interaction__C();
   Account acc= new Account();
        acc.Name='Test Account';
        insert acc;
  Contact con = new Contact(FirstName='TestClass',LastName='Test',AccountId=acc.Id);
  insert con;
  ApexPages.StandardController stdController;
  inte.Contact__c=con.Id;
  inte.Action_point__c='test';
  inte.Action_Point_date__c=Date.today();
  insert inte;
        
        
   Opportunity opp= new Opportunity();
   opp.Name= 'test opp';
   opp.StageName= 'shortlisted';
   opp.CloseDate = System.today().addDays(7);
  // opp.AccountId = accountId;
   opp.Interaction__c = inte.Id;
  
  
   opp.contact__c= con.id;
   //opp.Availability_Status__c = prod.open;
  
   
   
   insert opp;
   Accompaniment__c accment = new Accompaniment__c();
  // accment.Name='test tracker';
   accment.Role_Of_Accompaniment__c='Silent';
   accment.Interaction__c=inte.Id;
   insert accment;
   
   delete inte;
             Test.stopTest();
           
        }
    
}