SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <description>Campaign for profile</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/classes/TestHelperOppCampaignUpdate.cls
@isTest()
public class TestHelperOppCampaignUpdate {
    public static testMethod void testHelperOppCampaignUpdateMethod(){
        Test.startTest();
        
        //Creat test Account
        Account newAccount = new Account (name='Test Account');
        insert newAccount;
        //create first contact
        List<Contact> listcontact= new List<Contact>();
        Contact myContact = new Contact (FirstName='Test Profile',
        LastName='Test',
        AccountId=newAccount.id);
        listcontact.add(myContact);
        Contact myContact1 = new Contact (FirstName='Test Profile2',
        LastName='Test2',
        AccountId=newAccount.id);
        listcontact.add(myContact1);
        insert listcontact;
        
        
        
        
        //Campaign data  creation
        Campaign camp = new Campaign();
        camp.Name='Test Campaign';
        insert camp;
        
        
        
        //Interaction data
        Interaction__c interact = new Interaction__c();
        interact.Action_point__c='Test Data';
        interact.Action_Point_date__c=Date.today();
        interact.Contact__c=listContact.get(0).id;
        interact.Campaign__c=camp.id;
        insert interact;
        Interaction__c interact1 = new Interaction__c();
        interact1.Action_point__c='Test Data';
        interact1.Action_Point_date__c=Date.today();
        interact1.Contact__c=listContact.get(0).id;
        //interact1.Campaign__c=camp.id;
        insert interact1;
        //Opportunity data
        Opportunity opp = new Opportunity();
        opp.Name='test opp';
        opp.StageName='Seen';
        opp.CloseDate=date.today();
        opp.Interaction__c=interact.id;
        insert opp;
        Opportunity opp1 = new Opportunity();
        opp1.Name='test opp1';
        opp1.StageName='Seen';
        opp1.CloseDate=date.today();
        opp1.Interaction__c=interact1.id;
        insert opp1;
        Test.stopTest();
        
        
        HelperOppCampaignUpdate.updateCampaign(opp);
         HelperOppCampaignUpdate.updateCampaign(opp1);
        
    }
}