SFDC/src/objects/Accompaniment__c.object
<CustomObject>
    <description>This is the Relation that is linked to an Interaction.</description>
    <fields>
        <fullName>Interaction__c</fullName>
        <description>The Interaction to which this Accompaniment is related to.</description>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Accompaniments</relationshipLabel>
        <relationshipName>Accompaniments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation_Type__c</fullName>
        <label>Relation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relation__c</fullName>
        <description>The Relation that describes the Accompaniment.</description>
        <label>Relation</label>
        <referenceTo>Relation__c</referenceTo>
        <relationshipLabel>Accompaniments</relationshipLabel>
        <relationshipName>Accompaniments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Of_Accompaniment__c</fullName>
        <description>Role of the accompaniment</description>
        <label>Accompaniment Role</label>
        <picklist>
            <picklistValues>
                <fullName>Silent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Accompaniment</label>
    <nameField>
        <displayFormat>Accompaniment-{000}</displayFormat>
        <label>Accompaniment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accompaniments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Relation__c.object
<CustomObject>
    <description>Custom object to capture people as customer&apos;s accompaniments.</description>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <description>The parent contact to which this relation is linked to.</description>
        <inlineHelpText>The parent contact to which this relation is linked to.</inlineHelpText>
        <label>Parent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations</relationshipLabel>
        <relationshipName>P_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <description>The contact associated to this relationship.</description>
        <inlineHelpText>The contact associated to this relationship.</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations(Self)</relationshipLabel>
        <relationshipName>Relations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation_Type__c</fullName>
        <description>The type of Relationship</description>
        <label>Relation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relation</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Relation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/classes/triggerDeleteRelationTest.cls
@istest
public class triggerDeleteRelationTest{
    static testmethod void unittest(){
Test.startTest();
Account acc= new Account();
        acc.Name='Test Account';
        insert acc;
        contact c=new contact();
        c.lastname='greg';
        c.AccountId=acc.Id;
        insert c;
        Relation__c rel= new Relation__c();
        rel.Parent_Contact__c=c.Id;
        rel.Related_Contact__c=c.Id;
        rel.Relation_Type__c='son';
     
        insert rel;
   
      Interaction__C inte = new Interaction__C();
  
      inte.Contact__c=c.Id;
      inte.Action_point__c='Other';
      inte.Action_Point_date__c=Date.today();
      insert inte;
        
      
  
   Accompaniment__c accment = new Accompaniment__c();
  // accment.Name='test tracker';
   accment.Role_Of_Accompaniment__c='Silent';
   accment.Interaction__c=inte.Id;
   accment.Relation__C=rel.Id;
   insert accment;
   delete rel;
   
   Test.stopTest();
           
        }
    
}