SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Style_No__c</fullName>
        <description>External ID for Products</description>
        <externalId>true</externalId>
        <label>Style No</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

SFDC/src/classes/TestTaskReminder.cls
@isTest(seeAllData=true)

public class TestTaskReminder {
    // CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    static testmethod void test() {
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduleApexClassTest1',
                                       CRON_EXP,
                                       new ScheduleTaskReminderAndManagerEscalation());
        Account acc = new Account();
        acc.Name= 'Test family';
        insert acc;
        Contact con= new Contact(FirstName='test', LastName='test1');
        con.AccountId=acc.Id;                             
        insert con;
        
         Interaction__c inte= new Interaction__C();
         inte.Contact__c=con.Id;
        inte.Action_point__c='test';
       inte.Action_Point_date__c=Date.today();
      insert inte;         
      Product2 prod = new Product2(name='ProductTest',Style_no__c='testProd-001',IsActive=TRUE);       
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry();
      //pbe.pricebook2id=pb2.Id;
      pbe.Pricebook2Id=[select id from Pricebook2 where name='Standard Price Book' limit 1].id;
      pbe.Product2Id=prod.Id;
      pbe.IsActive=true;
      pbe.UnitPrice=10000;
      insert pbe;                     
        Opportunity opp = new Opportunity();
        opp.Name='Test Opp';
        opp.StageName='Seen';
        opp.Availability_Status__c=true;
        opp.Interaction__C=inte.Id;
        opp.CloseDate=Date.today().addDays(3);                                 
        insert opp;     
          OpportunityLineItem oli = new OpportunityLineItem();
           oli.UnitPrice=pbe.UnitPrice;//Unless you are pricing differently
           oli.Quantity=1;
           oli.PricebookEntryId=pbe.id;
           oli.OpportunityId = opp.Id;
           insert oli;    
      
        
        
        Task newTask = new Task();
       newTask.Subject='Activity Reminder - No Action Taken';      
       newTask.Status='Not Started';  
       newTask.Priority='Normal';
       newTask.IsReminderSet =true;
       newTask.ReminderDateTime=System.Now();
       newTask.Description='Activity Reminder - No Action Taken'; 
        newTask.ActivityDate=Date.today().addDays(3);
       //newTask.whatId=opid;
       //newTask.whoId=UserInfo.getUserId();
       newTask.OwnerId = [select id,name from user where name='Abdul Khan' limit 1].id;
       insert newTask;        
        
        
        Task newTask2 = new Task();
       newTask2.Subject='Activity Reminder - No Action Taken';      
       newTask2.Status='Not Started';  
       newTask2.Priority='Normal';
       newTask2.IsReminderSet =true;
       newTask2.ReminderDateTime=System.Now();
       newTask2.Description='Activity Reminder - No Action Taken'; 
        newTask2.ActivityDate=Date.today().addDays(-3);
       //newTask.whatId=opid;
       //newTask.whoId=UserInfo.getUserId();
       newTask2.OwnerId = [select id,name from user where name='Abdul Khan' limit 1].id;
       insert newTask2;   
        
        
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP,
                            ct.CronExpression);
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }        
}