SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/classes/InteractionExtensionTest.cls
@isTest

public class InteractionExtensionTest{

  static testMethod void testinteraction(){
  Interaction__C inte = new Interaction__C();
   Interaction__C inte1 = new Interaction__C();
   Account acc= new Account();
        acc.Name='Test Account';
        insert acc;
  Contact con = new Contact(FirstName='TestClass',LastName='Test',AccountId=acc.Id);
  insert con;
  ApexPages.StandardController stdController;
  inte.Contact__c=con.Id;
  inte.Action_point__c='test';
  inte.Action_Point_date__c=Date.today();
  insert inte;
  
  
  ApexPages.StandardController sc = new ApexPages.standardController(inte);
 // stdcontroller =acc;
  InteractionExtension accEx=new InteractionExtension(sc);
 /* 
  inte1.Contact__c=con.Id;
  inte1.Action_point__c='test';
  inte1.Action_Point_date__c=Date.today();
  inte1.Availability_Status__c= false;
  insert inte1;
  
  
  ApexPages.StandardController sc1 = new ApexPages.standardController(inte1);
 // stdcontroller =acc;
  InteractionExtension accEx1=new InteractionExtension(sc1);*/
  }
}