SFDC/src/objects/Accompaniment__c.object
<CustomObject>
    <description>This is the Relation that is linked to an Interaction.</description>
    <fields>
        <fullName>Interaction__c</fullName>
        <description>The Interaction to which this Accompaniment is related to.</description>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Accompaniments</relationshipLabel>
        <relationshipName>Accompaniments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation_Type__c</fullName>
        <label>Relation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relation__c</fullName>
        <description>The Relation that describes the Accompaniment.</description>
        <label>Relation</label>
        <referenceTo>Relation__c</referenceTo>
        <relationshipLabel>Accompaniments</relationshipLabel>
        <relationshipName>Accompaniments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Of_Accompaniment__c</fullName>
        <description>Role of the accompaniment</description>
        <label>Accompaniment Role</label>
        <picklist>
            <picklistValues>
                <fullName>Silent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Accompaniment</label>
    <nameField>
        <displayFormat>Accompaniment-{000}</displayFormat>
        <label>Accompaniment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accompaniments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Family Head</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Style_No__c</fullName>
        <description>External ID for Products</description>
        <externalId>true</externalId>
        <label>Style No</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

SFDC/src/objects/Relation__c.object
<CustomObject>
    <description>Custom object to capture people as customer&apos;s accompaniments.</description>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <description>The parent contact to which this relation is linked to.</description>
        <inlineHelpText>The parent contact to which this relation is linked to.</inlineHelpText>
        <label>Parent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations</relationshipLabel>
        <relationshipName>P_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <description>The contact associated to this relationship.</description>
        <inlineHelpText>The contact associated to this relationship.</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations(Self)</relationshipLabel>
        <relationshipName>Relations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation_Type__c</fullName>
        <description>The type of Relationship</description>
        <label>Relation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relation</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Relation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/classes/TestHelperRFMAnalysis.cls
/**
* Test class to unit test HelperRFMAnalysis. --- 
* @author Samir
* @date  10/20/2014(mm/dd/yy)
* @version 1.0
*/

@isTest(SeeAllData=false) 
public class TestHelperRFMAnalysis {
    public static testMethod void testHelperRFMAnalysis() {
        Test.startTest();
        
        Account newAccount = new Account (name='Test Account');
        insert newAccount;
        //create first contact
        List<Contact> listcontact= new List<Contact>();
        Contact myContact = new Contact (FirstName='Test Profile',
        LastName='Test',
        AccountId=newAccount.id);
        listcontact.add(myContact);
        Contact myContact1 = new Contact (FirstName='Test Profile2',
        LastName='Test2',
        AccountId=newAccount.id);
        listcontact.add(myContact1);
        insert listcontact;
        
        Interaction__c inte= new Interaction__C();
         inte.Contact__c=listcontact.get(0).id;
        inte.Action_point__c='test';
       inte.Action_Point_date__c=Date.today();
      insert inte; 
        
       Interaction__c inte1= new Interaction__C();
       inte1.Contact__c=listcontact.get(1).id;
       inte1.Action_point__c='test';
       inte1.Action_Point_date__c=Date.today();
       insert inte1; 
        
        
        Relation__c rel1= new Relation__c();
        rel1.Parent_Contact__c=listcontact.get(0).id;
        rel1.Related_Contact__c=listcontact.get(1).id;
        rel1.Relation_Type__c='son';
        insert rel1;
            

  
   Accompaniment__c accment = new Accompaniment__c();
   //accment.Name='test tracker';
   accment.Role_Of_Accompaniment__c='Silent';
   accment.Interaction__c=inte.Id;
   accment.Relation__C=rel1.id;
   insert accment; 
    
      
      Product2 prod = new Product2(name='ProductTest',Style_no__c='testProd-001',IsActive=TRUE);       
        insert prod;
        PricebookEntry pbe = new PricebookEntry();
      //pbe.pricebook2id=pb2.Id;
      pbe.Pricebook2Id=Test.getStandardPricebookId();
      pbe.Product2Id=prod.Id;
      pbe.IsActive=true;
      pbe.UnitPrice=100000000;
      insert pbe;     
        List<Opportunity> opplist=new LIST<Opportunity>();
       // for(integer i=1;i<6;i++)
               Opportunity opp = new Opportunity();
        opp.Name='Test Opp';
        opp.StageName='Bought';
        opp.Availability_Status__c=true;
        opp.Interaction__C=inte.Id;
        opp.Contact__c=listcontact.get(0).id;
        opp.CloseDate=Date.today().addDays(-300);                                 
        insert opp;    
       // } 
      //  insert opplist;
       // for(integer j=0;j<opplist.size();j++){
        OpportunityLineItem oli = new OpportunityLineItem();
           oli.UnitPrice=pbe.UnitPrice;//Unless you are pricing differently
           oli.Quantity=1;
           oli.PricebookEntryId=pbe.id;
           oli.OpportunityId = opp.Id;
           insert oli;
        //}    
        List<Opportunity> opplist2=new LIST<Opportunity>();
        for(integer i=1;i<=6;i++){
        Opportunity opp1 = new Opportunity();
        opp1.Name='Test Opp1';
        opp1.StageName='Bought';
        opp1.Availability_Status__c=true;
        opp1.Interaction__C=inte1.Id;
        opp1.Contact__c=listcontact.get(1).id;
        opp1.CloseDate=Date.today().addDays(-160*i);                                 
        opplist2.add(opp1);     
        } 
        insert opplist2;
        for(integer j=0;j<opplist2.size();j++){
        OpportunityLineItem oli1 = new OpportunityLineItem();
           oli1.UnitPrice=pbe.UnitPrice;//Unless you are pricing differently
           oli1.Quantity=1;
           oli1.PricebookEntryId=pbe.id;
           oli1.OpportunityId = opplist2.get(j).Id;
           insert oli1;
        }
 Opportunity opp3 = new Opportunity();
        opp3.Name='Test Opp';
        opp3.StageName='Bought';
        opp3.Availability_Status__c=true;
        opp3.Interaction__C=inte.Id;
        opp3.Contact__c=listcontact.get(0).id;
        opp3.CloseDate=Date.today().addDays(-300);                                 
        insert opp3;     
       // } 
      //  insert opplist;
       // for(integer j=0;j<opplist.size();j++){
        OpportunityLineItem oli3 = new OpportunityLineItem();
           oli3.UnitPrice=pbe.UnitPrice;//Unless you are pricing differently
           oli3.Quantity=1;
           oli3.PricebookEntryId=pbe.id;
           oli3.OpportunityId = opp3.Id;
           insert oli3;
        
        
        
        
        
        
        



        
        Set<id> contactIds = (new Map<Id,SObject>(listContact)).keySet();
        try{
            HelperRFMAnalysis.updateRFMAnalysis(contactIds);
            System.assert(TRUE);
        }catch(Exception e){
            System.assert(FALSE);
        }
    }
}