SFDC/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>This field is for lookup field in syncDataPage2</description>
        <label>Profile Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Point_date__c</fullName>
        <label>Action Point Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Associated_Store__c</fullName>
        <label>Associated Store</label>
        <picklist>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Profile</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>If_Time_Spent_on_Level_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Time Spent on Level 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>If_Time_Spent_on_Level_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Time Spent on Level 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interaction_Name__c</fullName>
        <formula>Contact__r.FirstName+&apos; &apos;+ Contact__r.LastName  &amp; IF(NOT(ISBLANK(text(Purpose_of_interaction__c))),&quot; (&quot; +  text(Purpose_of_interaction__c)+ &quot;) &quot;,&apos; &apos;) &amp;  Name</formula>
        <label>Interaction Name1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medium_of_Interaction__c</fullName>
        <label>Medium of Interaction</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting at external event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting instore event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Store appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Bought</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shortlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Will come back again</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_Rejection_Acceptance__c</fullName>
        <description>Reason for Buying/Rejection</description>
        <label>Reason for Buying/Rejection</label>
        <picklist>
            <picklistValues>
                <fullName>Craftmanship</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusivity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Comfortable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Specified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Staff_1__c</fullName>
        <label>Staff1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Spent_On_Level_1_in_Minutes__c</fullName>
        <label>Time Spent On Level 1 in Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Spent_On_Level_2_in_Minutes__c</fullName>
        <label>Time Spent On Level 2 in Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <inlineHelpText>Customer&apos;s product likability.</inlineHelpText>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Liked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disliked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

SFDC/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Style_No__c</fullName>
        <description>External ID for Products</description>
        <externalId>true</externalId>
        <label>Style No</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

SFDC/src/objects/RemoteSessionData__c.object
<CustomObject>
    <description>Holds information of hand held device session information(Customer and his chosen products) , synched to this salesforce instance.</description>
    <fields>
        <fullName>Action_point_Date__c</fullName>
        <label>Action point Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_point__c</fullName>
        <label>Action point</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date/Time</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>If_Time_Spent_on_Level_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Time Spent on Level 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>If_Time_Spent_on_Level_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Time Spent on Level 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interaction_Name__c</fullName>
        <label>Interaction Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Reason_for_Acceptance_or_Rej__c</fullName>
        <label>Interaction Reason for Acceptance or Rej</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ipad_Username__c</fullName>
        <label>Sales User&apos;s EmailId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medium_of_Interaction__c</fullName>
        <label>Medium of Interaction</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Reason_for_acceptance_rejection__c</fullName>
        <label>Opp Reason for acceptance/rejection</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <label>Opportunity Stage</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Style_No__c</fullName>
        <externalId>true</externalId>
        <label>Product Style No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>RemoteSessionData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_User_s_Name__c</fullName>
        <label>Sales User&apos;s Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SessionID__c</fullName>
        <description>Session ID of Remote.</description>
        <externalId>true</externalId>
        <label>Ipad User Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date/Time</description>
        <inlineHelpText>Start Date/Time of Interaction</inlineHelpText>
        <label>Start Date/Time</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Spent_On_Level_1_in_Minutes__c</fullName>
        <label>Time Spent On Level 1 in Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Spent_On_Level_2_in_Minutes__c</fullName>
        <label>Time Spent On Level 2 in Minutes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Soft Delete</inlineHelpText>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>IpadSyncData</label>
    <nameField>
        <displayFormat>RSD-{0000000000}</displayFormat>
        <label>RemoteSessionData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IpadSyncData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/classes/syncDataController.cls
public class syncDataController {

   // public String interact { get; set; }
    
    private final RemoteSessionData__c syncdata;
    public List<AggregateResult> listSessionProfiles{get;set;}  
    public List<AggregateResult> finallist{get;set;}
    public list<Product2> listOpportunityProducts  {get;set;} 
    public list<remoteSessionData__c> listOppProdsOutOfSync = new List<remoteSessionData__C>();
    public List<cProduct> selectedProducts {get;set;} 
    public Integer listsize {get;set;}
    public Integer productListsiZe {get;set;}
    public String val1{get;set;}  
    public String val2{get;set;}
    
    public  List<cProduct> productList{get;set;}
    
    public Contact contact {get;set;}   
    public List<contact> listCon ;  
    public List<remoteSessionData__c> listRSDSetFlag ;
    public  List<remoteSessionData__c> updatelistRSDSetFlag = new List<remoteSessionData__C>();
    
    public List<remoteSessionData__c> listRSDSetFlag1 ;
    public  List<remoteSessionData__c> updatelistRSDSetFlag1 = new List<remoteSessionData__C>();
    public String contactId;
    public String accountId;
    public String interactionId;    
    public list<string> duplicateProductsName= new list<string>();   
    public boolean isDeleted {get; set;}
    public boolean displayPopup {get; set;} 
    public boolean showMessage{get; set;}  
    public boolean outOfSyncNotice {get; set;}  
    public string actionPointText {get; set;} 
    public interaction__c aInteract {get; set;} 
   
    
    
    
    // Change Set 20 Ipad Sync Issue on 8th May 2015 starts here- @Ranga----------------------------
    /*
    private final Product2 prod;
     public SyncDataController(ApexPages.StandardController stdController) {
        this.prod = (Product2)stdController.getRecord();
        
      }
    */
    
    // Change Set 20 Ipad Sync Issue on 8th May 2015 Ends here- @Ranga----------------------------
    
    
    
    public syncDataController() {
    
        //String loggedInUsername = user.name;
        aInteract = new Interaction__C();
        contact = new Contact();
        selectedproducts= new List<cproduct>();
        if(ApexPages.CurrentPage().getParameters().get('profileId')!=null){
        contact.Profile_name__C=ApexPages.CurrentPage().getParameters().get('profileId');
        }
        String userName = UserInfo.getUserName();
        
        User activeUser = [Select Email From User where Username = : userName limit 1];
        String userEmail = activeUser.Email;
        system.debug('Active userEmail:' +userEmail);
        //listSessionProfiles = [Select SessionID__c,Customer_Name__c,Ipad_UserName__c from RemoteSessionData__c group by SessionID__c,Customer_Name__c,Ipad_Username__c ];
        listSessionProfiles = [Select SessionID__c,Customer_Name__c,Sales_User_s_Name__c,Interaction_Name__c,day_only(createdDate) createdonDate,count(createdDate) numCreated from RemoteSessionData__c where Ipad_UserName__c=:useremail and isDeleted__c != true group by day_only(createdDate),Interaction_Name__c,SessionID__c, Customer_Name__c,Sales_User_s_Name__c order by day_only(createdDate) desc];
                
        listsize = 0;
        productListSize=0;
        listOppProdsOutOfSync.clear();
        OutOfSyncNotice=false;
        
    } 
    
    
    
    
    public PageReference syncDataPage2() 
    {  
        // Your code here
        val1 = ApexPages.CurrentPage().getParameters().get('val1');
        val2 = ApexPages.CurrentPage().getParameters().get('val2');
        
        system.debug('val1: '+val1 +' val2: '+val2 );
        PageReference redirect = new PageReference('/apex/syncDataPage2'); 
        
        
        try{
            listOpportunityProducts =[select ProductCode, Style_No__c, Name,Material__c, (Select SessionID__c, product__c, product__r.name, product__r.Style_No__c, Customer_Name__c, Interaction_Name__c,                                   Interaction_Reason_for_Acceptance_or_Rej__c, Opp_Reason_for_acceptance_rejection__c, Medium_of_Interaction__c, 
                                                                                          Opportunity_Stage__c, Outcome__c, Product_Status__c, Product_Style_No__c, Ipad_Username__c, Sales_User_s_Name__c, Start_Date__c,
                                                                                          Action_point__c, Action_point_Date__c, Availability__c,If_Time_Spent_on_Level_1__c,If_Time_Spent_on_Level_2__c,
                                                                                          Time_Spent_On_Level_1_in_Minutes__c,Time_Spent_On_Level_2_in_Minutes__c,start_date_time__c,End_Date_Time__c from RemoteSessionData__r where SessionID__c=:val1 and Customer_Name__c=:val2  ) 
                                      from product2 where id in (Select product__c from RemoteSessionData__c where SessionID__c=:val1 and Customer_Name__c=:val2 ) ];
            listsize = listOpportunityProducts.size();
            system.debug('listsize:'+listsize);
            /*if(listSize == 0) 
            {
                throw new syncException();
            }    */                 
            
            
            listOppProdsOutOfSync =[Select Product_Style_No__c from RemoteSessionData__c where SessionID__c=:val1 and Customer_Name__c=:val2 and Product__c=null ];
            system.debug( 'listOppProdsOutOfSync' +listOppProdsOutOfSync);
            
            
             if(listOppProdsOutOfSync.size() > 0){ 
                    OutOfSyncNotice = true;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'The products with the below Style number are not available in Salesforce'));   
                   
                 for(RemoteSessionData__c outOfSync :listOppProdsOutOfSync ) {
                     // System.debug('list opp products-----------------'+outOfSync.Product_Style_No__c);  
                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,+outOfSync.Product_Style_No__c));
                    }   
                    
            }   
            
            
        }
       
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'YOUR MESSAGE HERE'));
            return null;
        }
        
        
        
      //  system.debug('listOpportunityProducts: '+listOpportunityProducts);
        
        
        
        
        productList= new List<cProduct>();
        
        
        for(Product2 c:listOpportunityProducts  ) {
            system.debug('productList in iteration: '+c );
            productList.add(new cProduct(c,c.RemoteSessionData__r.get(0).Opportunity_Stage__c,c.RemoteSessionData__r.get(0).Product_Status__c,c.RemoteSessionData__r.get(0).Opp_Reason_for_acceptance_rejection__c,c.remoteSessionData__r.get(0).Availability__c));
            
        }
        
        
        system.debug('productList size: '+productList.size());
        productListSize = productList.size();
        
        redirect.setRedirect(false); 
        return redirect;
        
    }
    
    public dateTime dateFormatConversion(String dateString){
     
   dateString = '"' +dateString +'"';
   
   DateTime  dt = (Datetime)json.deserialize(dateString, datetime.class);
     
   system.debug('DateTime StartTime and EndTime:' +dt  +dateString);  
     
     return dt;  
     
      /* String[] stringdatesplit=dateString.split('T');
              string datetimetest=dateString.substring(0,10);
              String datetimeonly=dateString.substring(11,16);
        
        String stringDate = datetimetest + ' ' +datetimeonly;
                
        return stringDate;  */
        
        
        
        
        
    }
    
    public PageReference addProduct(){  
        
        
        
         System.debug('action point date-----------------------------------------' +aInteract.Action_Point_date__c);
      //List<cProduct> selectedProducts = new LIST<cProduct>();
        
        for(cProduct cprod:productList ) {
            
            if(cprod.selected == true) {
                selectedProducts.add(cprod);
                // system.debug('selected Products:' +selectedProducts);
                
            }
        } 
        
        If(contact.Profile_Name__c == null){
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Please choose a profile name'));
                return null;
        
        }
        
        system.debug('selectedproductList size: '+selectedProducts.size());
        if(selectedProducts.size()==0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'No opportunity is selected.Please select a product to create an opportunity'));
                return null;
           }
        
        
        listCon  = [select id,accountID from contact where Id =: contact.Profile_Name__c Limit 1  ];
        if(listCon!=null && listCon.size()>0){
            Interaction__c interact = new interaction__c();
            interact.Contact__c=listCon.get(0).id;
            interact.Account__c=listCon.get(0).accountId;
            String dateActionPoint = ApexPages.CurrentPage().getParameters().get('actionpointdate');
                     
             
            interact.Action_point_date__c =aInteract.Action_Point_date__c;
             interact.Associated_Store__C =aInteract.Associated_Store__C;
             interact.Staff_1__c =aInteract.Staff_1__c;
            interact.Action_Point__c= aInteract.Action_Point__C;
                   
            interact.Medium_of_Interaction__c= listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Medium_of_Interaction__c;
            
            /*
               Any new Fields can be added here.....
               Ex: interact.Staff_1__c =aInteract.Staff_1__c;
            */
            
            
            /*
               Changes ends here
            */
            
            
           // interact.Reason_for_Rejection_Acceptance__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Interaction_Reason_for_Acceptance_or_Rej__c;
            interact.Outcome__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Outcome__c;
            interact.Start_Time__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Start_Date__c;
            
            
            
             interact.If_Time_Spent_on_Level_1__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).If_Time_Spent_on_Level_1__c;
            interact.If_Time_Spent_on_Level_2__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).If_Time_Spent_on_Level_2__c;
            interact.Time_Spent_On_Level_1_in_Minutes__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Time_Spent_On_Level_1_in_Minutes__c;
            interact.Time_Spent_On_Level_2_in_Minutes__c=listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Time_Spent_On_Level_2_in_Minutes__c;
           // if(listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Start_Date_Time__c!= null) interact.Start_Time__c= dateFormatConversion(listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Start_Date_Time__c);
            if(listOpportunityProducts.get(0).RemoteSessionData__r.get(0).End_Date_Time__c!= null) interact.End_Time__c=  dateFormatConversion(listOpportunityProducts.get(0).RemoteSessionData__r.get(0).End_Date_Time__c);
            // system.debug('listOpportunityProducts-medium of interaction:' + listOpportunityProducts.get(0).RemoteSessionData__r.get(0).Medium_of_Interaction__c);
            insert interact;
            
            interactionId=interact.id;
            contactID= listCon.get(0).id;
            accountId=listCon.get(0).accountId;
        }
        
        
       
        duplicateProductsName  = HelperAddProducts.addProductsToInteraction(selectedProducts, contactId, accountID, interactionID); 
        
        
        if(duplicateProductsName.size()>0)   
        {  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Opportunities have been created for the products selected however opportunities for below products already exists as part of same or previous interactions:')); 
         for(string prodName : duplicateProductsName  ){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,+prodName));
         }
         duplicateProductsName.clear();
         return null;
        } 
        
        system.debug('isDeleted:' +isdeleted);  
        
        if(isDeleted == true){
            
            listRsdSetFlag = [Select sessionId__c,isDeleted__c from RemoteSessionData__c where SessionID__c=:val1 ];
            system.debug('listRsdSetFlag:' +listRsdSetFlag );
            for(RemoteSessionData__c rd : listRsdSetFlag ){
                
                rd.isDeleted__c = true;
                updatelistRSDSetFlag.add(rd);
            }
            if(updatelistRSDSetFlag!= null){
                update(updatelistRSDSetFlag);
            }
        } 
        
        
        PageReference pr = new PageReference('/' +interactionID );
        pr.setRedirect(true);
        
        displayPopup = true;
        
        
        return null;
    }
    
    public PageReference enableCreateOpp(){
        
        for(cProduct prod: productList) {
            // cProduct cProd;
            System.debug('Selected Opp Stagee-----------------------'+prod.selectedOpp);
            if(prod.selectedOpp=='Shortlisted'){
                prod.open=true;
            }
            else{
                prod.open=false;
            }
            
        }
        return null;
    }
     
    
    
    
    
   
    public void showPopup()
    { 
        
        displayPopup = true; 
        
    } 
    
    public PageReference closePopup()
    { 
        displayPopup = false; 
        //PageReference pr = new PageReference(); 
        //pr.setRedirect(true); 
        return null;
        
    }      
    
    
    
    public PageReference okay(){
        
        PageReference pr = new PageReference('/' +interactionID );
        pr.setRedirect(true);
        return pr;       
    }    
    public PageReference cancel(){
        
          String tabId= ApexPages.currentPage().getParameters().get('sfdc.tabName');
        string onCancel = 'apex/syncDataPage?sfdc.tabName=';
                        PageReference pr = new PageReference('/' +onCancel+tabId);
                        pr.setRedirect(true);
                 return pr;
                    }
  
    
    public PageReference deleteSession(){
        
        
        listRsdSetFlag1 = [Select sessionId__c,isDeleted__c from RemoteSessionData__c where SessionID__c=:val1 ];
        system.debug('listRsdSetFlag:' +listRsdSetFlag1 );
        for(RemoteSessionData__c rd : listRsdSetFlag1 ){
            
            rd.isDeleted__c = true;
            updatelistRSDSetFlag1.add(rd);
        }
        if(updatelistRSDSetFlag1!= null){
            update(updatelistRSDSetFlag1);
        }
        
        
         String tabId= ApexPages.currentPage().getParameters().get('sfdc.tabName');
        string onDelete = 'apex/syncDataPage?sfdc.tabName=';
        PageReference pr = new PageReference('/' +onDelete+tabId);
        pr.setRedirect(true);
        return pr;
        
    }  
}