SFDC/src/objects/Interaction__c.object
<CustomObject>
    <description>Custom object to capture details of an Interaction with a customer.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>Interaction ID- {0000}</displayFormat>
        <label>Interaction External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <referenceTo>Interaction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC/src/classes/HelperOppCampaignUpdate.cls
/**
 * Helper class for updating Opportunities with the same Campaign as that of its Interaction. --- 
 * @author Samir
 * @date  09/14/2014(mm/dd/yy)
 * @version 1.0
 */

global class HelperOppCampaignUpdate {
    
    /**
     * An asynchronous method to update the Opportunity's Campaign with that of its Interaction.
    **/
    //@future
    public static void updateCampaign(Opportunity opp){
        System.debug('BEFOREUPDATE  ');
        
        List<Interaction__c> listInteractions = [SELECT Id,Campaign__c from Interaction__c where Id= :opp.Interaction__c];
        
        if(listInteractions != null && listInteractions.get(0).Campaign__c != null){
            opp.CampaignId = listInteractions.get(0).Campaign__c;
            System.debug('BEFOREUPDATE  '+ listInteractions.get(0).Campaign__c);
            try{
                update opp;
            }catch(Exception e){
                System.debug('Exception while updating Opportunitys Campaign  '+ e);
            }
            
        }
    }    
}