SFDC/src/objects/Relation__c.object
<CustomObject>
    <description>Custom object to capture people as customer&apos;s accompaniments.</description>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <description>The parent contact to which this relation is linked to.</description>
        <inlineHelpText>The parent contact to which this relation is linked to.</inlineHelpText>
        <label>Parent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations</relationshipLabel>
        <relationshipName>P_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <description>The contact associated to this relationship.</description>
        <inlineHelpText>The contact associated to this relationship.</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relations(Self)</relationshipLabel>
        <relationshipName>Relations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation_Type__c</fullName>
        <description>The type of Relationship</description>
        <label>Relation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nephew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relation</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Relation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC/src/classes/TestRelationExtension.cls
@isTest

public class TestRelationExtension {
    
    public static testMethod void testMyController() {
        
        Test.startTest();
        Account newAccount = new Account (name='Test Account');
        insert newAccount;
        //create first contact
        List<Contact> listcontact= new List<Contact>();
        Contact myContact = new Contact (FirstName='Test Profile',
                                         LastName='Test',
                                         AccountId=newAccount.id);
        listcontact.add(myContact);
        Contact myContact1 = new Contact (FirstName='Test Profile2',
                                          LastName='Test2',
                                          AccountId=newAccount.id);
        listcontact.add(myContact1);
        
        insert listcontact;
        Relation__c rel = new Relation__c();
        rel.Related_Contact__c=listcontact.get(0).Id;
        rel.Parent_Contact__c=mycontact.Id;
        rel.Relation_Type__c='Son';
        insert rel;
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rel);
        RelationExtension relationExtension = new RelationExtension(stdController);
        relationExtension.Cancel();
        //PageReference p = new PageReference('/apex/CustomRelation'); 
        //Test.setCurrentPage(p);
        //RelationExtension relExt = new RelationExtension();
        PageReference p = relationExtension.save();
        // String nextPage=relationExtension.save().getUrl(); 
        //System.assertEquals('/null',nextPage);
        
        
        /*
        Relation__c rel1 = new Relation__c();
        rel1.Related_Contact__c=listcontact.get(0).Id;
        rel1.Parent_Contact__c=mycontact.Id;
        rel1.Relation_Type__c='Son';
        insert rel1;
        
        
        ApexPages.StandardController stdController1 = new ApexPages.StandardController(rel1);
        RelationExtension relationExtension1 = new RelationExtension(stdController1);
        
        //PageReference p = new PageReference('/apex/CustomRelation'); 
        //Test.setCurrentPage(p);
        //RelationExtension relExt = new RelationExtension();
        PageReference p1 = relationExtension1.save();
        //   String nextPage1=relationExtension1.save().getUrl(); 
        
        */
        
    }
}