SFDC/src/objects/RemoteSessionData__c.object
<CustomObject>
    <description>Holds information of hand held device session information(Customer and his chosen products) , synched to this salesforce instance.</description>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ipad_Username__c</fullName>
        <label>Sales User&apos;s EmailId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>RemoteSessionData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessionID__c</fullName>
        <description>Session ID of Remote.</description>
        <externalId>true</externalId>
        <label>Ipad User Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IpadSyncData</label>
    <nameField>
        <displayFormat>RSD-{0000000000}</displayFormat>
        <label>RemoteSessionData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IpadSyncData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/classes/IpadSyncSOAPWebservice.cls
global class IpadSyncSOAPWebservice {
    webService static Id createRemoteSession(String customerName,String ipadusername, String product,String session,String sessionId) {
        
        RemoteSessionData__c sessionData = new RemoteSessionData__c();
        sessionData.Customer_Name__c= customerName;
        sessionData.Ipad_Username__c= ipadusername;
        sessionData.Product__c= product;
        sessionData.SessionID__c=session;
        insert sessionData;
        return sessionData.Id;
    }
    
    /*webService static Id login(String username,String password) {
        RemoteSessionData__c sessionData = new RemoteSessionData__c();
        sessionData.Customer_Name__c= customerName;
        sessionData.Ipad_Username__c= ipadusername;
        sessionData.Product__c= product;
        sessionData.SessionID__c=session;
        insert sessionData;
        return sessionData.Id;
    }*/
    
       
}