SFDC/src/objects/RemoteSessionData__c.object
<CustomObject>
    <description>Holds information of hand held device session information(Customer and his chosen products) , synched to this salesforce instance.</description>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Name__c</fullName>
        <label>Interaction Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ipad_Username__c</fullName>
        <label>Sales User&apos;s EmailId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_User_s_Name__c</fullName>
        <label>Sales User&apos;s Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SessionID__c</fullName>
        <description>Session ID of Remote.</description>
        <externalId>true</externalId>
        <label>Ipad User Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Soft Delete</inlineHelpText>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>IpadSyncData</label>
    <nameField>
        <displayFormat>RSD-{0000000000}</displayFormat>
        <label>RemoteSessionData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IpadSyncData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/classes/SortClass.cls
public class SortClass {   
       public List<AggregateResult> listSessionProfiles{get;set;} 
        
        public SortClass(){
               listSessionProfiles= [Select Id,SessionID__c,Customer_Name__c,Sales_User_s_Name__c,Interaction_Name__c from RemoteSessionData__c where Ipad_UserName__c='eynmjfs@gmail.com' and isDeleted__c != true  group by Id,SessionID__c,Customer_Name__c,Sales_User_s_Name__c,Interaction_Name__c];
            
        }
 public void sortList(List<RemoteSessionData__c> listSessionProfiles, String order){

 
       List<RemoteSessionData__c> resultList = new List<RemoteSessionData__c>();
   
        //Create a map that can be used for sorting 
       Map<object, List<RemoteSessionData__c>> objectMap = new Map<object, List<RemoteSessionData__c>>();
       
       for(RemoteSessionData__c ob : listSessionProfiles){
                if(objectMap.get(ob.get(RemoteSessionData__c.createddate)) == null){  // For non Sobject use obj.ProperyName
                    objectMap.put(ob.get(RemoteSessionData__c.createddate), new List<RemoteSessionData__c>()); 
                }
                objectMap.get(ob.get(RemoteSessionData__c.createddate)).add(ob);
        }       
        //Sort the keys
        List<object> keys = new List<object>(objectMap.keySet());
        keys.sort();
       
        for(object key : keys){ 
            resultList.addAll(objectMap.get(key)); 
        }
       
        //Apply the sorted values to the source list
        listSessionProfiles.clear();
        if(order.toLowerCase() == 'asc'){
            for(RemoteSessionData__c ob : resultList){
                listSessionProfiles.add(ob); 
            }
        }else if(order.toLowerCase() == 'desc'){
            for(integer i = resultList.size()-1; i >= 0; i--){
                listSessionProfiles.add(resultList[i]);  
            }
        }
    
 System.debug('descending order list-------------'+listSessionProfiles);
 }
    }