SFDC/src/objects/RemoteSessionData__c.object
<CustomObject>
    <description>Holds information of hand held device session information(Customer and his chosen products) , synched to this salesforce instance.</description>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ipad_Username__c</fullName>
        <label>Sales User&apos;s EmailId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>RemoteSessionData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessionID__c</fullName>
        <description>Session ID of Remote.</description>
        <externalId>true</externalId>
        <label>Ipad User Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IpadSyncData</label>
    <nameField>
        <displayFormat>RSD-{0000000000}</displayFormat>
        <label>RemoteSessionData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IpadSyncData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC/src/classes/IpadSyncRestService.cls
@RestResource(urlMapping='/RemoteSessionData__c/*')
global with sharing class IpadSyncRestService {

   /* @HttpGet
    global static RemoteSessionData__c doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String sessionId= req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        System.debug('session id-----------------'+sessionid);
        RemoteSessionData__C result = [SELECT Id, Product__c FROM RemoteSessionData__c WHERE ID = :sessionId];
        return result;
    }
  
  
    global static String doPost(String customerName,String ipadusername, String product,String session) {
        RemoteSessionData__c sessionData = new RemoteSessionData__c();
        RestRequest req = RestContext.request;
      //  req.addHeader('Authorization', '00DQ000000GK3pW!ARIAQMtLf_cPFOogDA4N3Y8Li2OVyem7WqkHy_WxuI4mDTSnhYpgzkhWF5FS8UnH3xvuMmRpvlcWxPjl.LjwQJwn.imYp5HU');
        sessionData.Customer_Name__c= customerName;
        sessionData.Ipad_Username__c= ipadusername;
        sessionData.Product__c= product;
        sessionData.SessionID__c=session;
        insert sessionData;
        return sessionData.Id;
    }*/
    @HttpPost
    global static RSDWrapper doPost(List<RemoteSessionData__c> SyncIpadDataList) {
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        RSDWrapper response = new RSDWrapper();
        
        try {
            insert SyncIpadDataList;
            response.rsdList = SyncIpadDataList;
            response.status = 'Success';
            response.message = 'Your Ipad data have been created successfully';
        }
        catch(Exception exc) {
            res.StatusCode = 500;
            response.rsdList= null;
            response.status = 'Error';
            response.message = 'Your request failed with the following error: ' + exc.getMessage();
        }
        
        return response;
        
        
    }



 global class RSDWrapper {
        public List<RemoteSessionData__c> rsdList;
        public String status;
        public String message;
        
        public RSDWrapper(){
            rsdList = new List<RemoteSessionData__c>();
        }
    }


    
}